name: Verify Build

on:
  push:
    branches: [ main, citest ]
  pull_request:
  workflow_dispatch:

jobs:
  
  android_version_tests:
    name: Android version tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - name: Setup ZULU_JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17.0.16+8
          distribution: 'zulu'
      - name: Set ZULU_JDK environment variable
        run: |
          echo "ZULU_JDK=$JAVA_HOME" >> $GITHUB_ENV
      - name: Setup ZULU_ALT_JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17.0.10+7
          distribution: 'zulu'
      - name: Set ZULU_ALT_JDK environment variable
        run: |
          echo "ZULU_ALT_JDK=$JAVA_HOME" >> $GITHUB_ENV
      - name: Set up Java 11
        uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Run integration tests
        run: >-
            ./gradlew assembleDebug -Porg.gradle.java.installations.auto-download=false
        env:
          DEVELOCITY_ACCESS_KEY : ${{ secrets.ACCESS_KEY }}
